### PR TITLE
Add ProjectionError as ValidationReport

### PR DESCRIPTION
**Pull request by jmirabel**
Solves #209

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
If you have tested, I let you merge.
Will this PR enable the manipulation steering method to fail with a more explicit message than "Steering method failed to build a path" ?

**Comment by jmirabel** [comment]
The message will mostly be useful when a user forgets to use a path projector. I don't think it can change the message "failed to build a path" since this does not affect the steering method.

**Comment by jmirabel** [comment]
This PR also contains a fix for https://github.com/humanoid-path-planner/hpp-core/pull/208#discussion_r410203425

@nim65s do you want to include this in #211

**Comment by nim65s** [comment]
I guess it removes the eneed for the `CMAKE_CXX_STANDARD`, right ? 

If so, yes, definitely, I can remove the commit about that in #211 and use this instead, thanks a lot !

**Comment by jmirabel** [comment]
> I guess it removes the need for the `CMAKE_CXX_STANDARD`, right ?

to be double-checked. I blindly follow the compilation error @pFernbach mentionned.

**Comment by pFernbach** [comment]
I confirm that with the commit https://github.com/humanoid-path-planner/hpp-core/pull/210/commits/d79d4055447795f1027f549be6ce74669fdf89a2 I can compile on 16.04 without requiring the `CMAKE_CXX_STANDARD` change. Thanks!

**Comment by jmirabel** [comment]
@nim65s I let you merge when it suits you.
